dj_test/apps/main_page/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'main_page'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('home/', views.home, name='home'),
    path('create_article/', views.create_article, name='create_article'),
    path('<int:article_id>/delete_article/', views.delete_article, name='delete_article'),
    path('<int:comment_id>/delete_comment/', views.delete_comment, name='delete_comment'),
    path('login', views.UserLoginView.as_view(), name='login_page'),
    path('logout', views.UserLogoutView.as_view(), name='logout_page'),
    path('register', views.usersignup, name='register_page'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate_account, name='activate'),
]

dj_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('dj_test.apps.main_page.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]

dj_test/apps/main_page/models.py
from django.utils import timezone

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class Article(models.Model):
    article_title = models.CharField('Название статьи', max_length=200)
    article_text = models.TextField('Текст статьи')
    pub_date = models.DateTimeField('Время публикации', default=timezone.now())
    author_name = models.CharField('name', max_length=50, default='')

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.article_title + ' ' + self.article_text


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment_text = models.CharField('comment', max_length=200)
    author_name = models.CharField('name', max_length=50)
    pub_date = models.DateTimeField('Время публикации', default=timezone.now())

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.comment_text


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    is_verified = models.BooleanField(verbose_name='Подтверждён', default=False)
    is_voted = models.BooleanField(verbose_name='Проголосовал', default=False)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if not Profile.objects.filter(user=instance).exists():
        create_user_profile(sender, instance, created=True)
    instance.profile.save()

dj_test/apps/main_page/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.forms import CharField, PasswordInput

class AuthUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class RegisterUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'] = CharField(widget=PasswordInput())

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].help_text = None

dj_test/apps/main_page/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.utils import timezone
import logging

from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import CreateView

from .forms import AuthUserForm, RegisterUserForm
from .models import Article, Comment
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy

from .token_generator import account_activation_token

logger = logging.getLogger('django')


def index(request):
    latest_news = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'arcticles/list.html', {'latest_news': latest_news})


def detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    l = article.comment_set.order_by('-id')[:10]
    return render(request, 'arcticles/detail.html', {'article': article, 'l': l})


@login_required
def leave_comment(request, article_id):
    a = get_object_or_404(Article, id=article_id)
    a.comment_set.create(author_name=request.user.username, comment_text=request.POST['text'], pub_date=timezone.now())
    return HttpResponseRedirect(reverse('main_page:detail', args=(a.id,)))


@login_required
def create_article(request):
    name = request.user.username
    Article.objects.create(article_title=request.POST.get('name'), article_text=request.POST.get('text'),
                           pub_date=timezone.now(), author_name=name)
    return HttpResponseRedirect(reverse('main_page:index'))


def home(request):
    return render(request, 'arcticles/home.html')


def delete_article(request, article_id):
    a = get_object_or_404(Article, id=article_id)
    a.delete()
    return HttpResponseRedirect(reverse('main_page:index'))


def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    a = comment.article
    return HttpResponseRedirect(reverse('main_page:detail', args=(a.id,)))


class UserLoginView(LoginView):
    template_name = 'login_form.html'
    form_class = AuthUserForm
    success_url = reverse_lazy('main_page:home')

    def get_success_url(self):
        logger.info('Successfully going to home page')
        return self.success_url


class UserLogoutView(LogoutView):
    next_page = reverse_lazy('home')


class UserRegisterView(CreateView):
    model = User
    template_name = 'register_form.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('home')
    success_msg = "Аккаунт успешно создан!"

    def form_valid(self, form):
        form_valid = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        auth_user = authenticate(username=username, password=password)
        login(self.request, auth_user)
        logger.info("User " + username + " is successfully register")

        return form_valid


def usersignup(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)

            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            email_subject = 'Активация аккаунта'
            message = render_to_string('activate_account.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(email_subject, message, to=[to_email])
            email.send()
            return HttpResponse('Мы отправили вам письмо, пожалуйста, подтвердите ваш e-mail для завершения регистрации!')
    else:
        form = RegisterUserForm()

    return render(request, 'register_form.html', {'form': form})


def activate_account(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        login(request, user)
        return HttpResponse('Your account has been activate successfully')
    else:
        return HttpResponse('Activation link is invalid!')

dj_test/apps/main_page/templates/activate_account.html
{% autoescape off %}
Hi {{ user.username }},
Пожалуйста перейдите по ссылке для подтверждения регистрации,
http://{{ domain }}{% url 'main_page:activate' uidb64=uid token=token %}
{% endautoescape %}

dj_test/apps/main_page/templates/base.html
<!DOCTYPE html>
<html lang="ru">
 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <title>{% block title %} My site {% endblock %}</title>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
      <ul class="sidebar-nav">
          <br/>
          <li><a href="{% url 'main_page:home'%}">Home</a></li>
          <li><a href="{% url 'main_page:index'%}">All posts</a></li>
             {% if user.is_authenticated %}
          <li>User: {{ user.get_username }}</li>
          <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
    {% else %}
          {% url 'main_page:login_page' as url_login %}
          <li class="nav-item"><a class="nav-link {% if url_login == request.path %} active{% endif %}" href="{{ url_login }}">Login</a></li>
              <li class="nav-item">
      {% url 'main_page:register_page' as url_register %}
    <a class="nav-link {% if url_register == request.path %} active{% endif %}" href="{{ url_register }}">Register</a>
  </li>
   {% endif %}
      </ul>
     {% endblock %}
            </div>
      <div class="col-sm-10 ">

    {% block content%} {% endblock %}
 </div>
    </div>
  </div>
</body>
</html>

dj_test/apps/main_page/templates/login_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1 class="mt-4">Авторизация</h1>

    <div class="col-4">
    <form id = "add_form" method="post">
    {% csrf_token %}
    {{ form }}
    <button form="add_form" type="submit" class = "btn btn-primary mt-4">Войти</button>
    </form>
    </div>

{% endblock %}

dj_test/apps/main_page/templates/register_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1 class="mt-4">Регистрация</h1>

    <div class="col-4">
    <form id = "add_form" method="post">
    {% csrf_token %}
    {{ form }}
    <button form="add_form" type="submit" class = "btn btn-primary mt-4">Зарегистрироваться</button>
    </form>
    </div>

{% endblock %}